### ISSUE TITLE
WackoWiki markup outside of WackoWiki

### ISSUE THREAD

**Issue by tobimensch** [WackoWiki/wackowiki#2]
The WackoWiki markup makes sense to me.

Is it supported anywhere outside of WackoWiki itself?

**Comment by vendeeglobe** [comment]
The WackoWiki markup is around since 2003 and there are a few other applications using the WackoWiki markup. Are you looking for implementations other than PHP or do you want implement the WackoWiki syntax in your application?

https://wackowiki.org/doc/Dev/Projects/WackoFormatter

**Comment by tobimensch** [comment]
Yes, I'm looking for implementations other than PHP.

**Comment by vendeeglobe** [comment]
On GitHub two other formatters are tagged with wackowiki, if you search further you find probably more.
The question is what you are looking exactly for. The most straight forward approach may be using an existing formatter/lexer and extend it for the use of the WackoWiki markup.
