### ISSUE TITLE
Please support docker install

### ISSUE THREAD

**Issue by kingwrcy** [WackoWiki/wackowiki#8]
I search on dockerhub,no WackoWiki image found,could you please add Docker Image ?

**Comment by vendeeglobe** [comment]
Please use a generic PHP/Apache container, mount some local volume and extract a WackoWiki tarball there. 

Its very unlikely that there will ever be a official WackoWiki docker image from the project maintainers.

Its up to the user community to provide a WackoWiki docker image.

https://hub.docker.com/search?q=wackowiki
